name: 'testpy20220426'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 16,22 * * *'

jobs:
  testpy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: python -m pip install requests
      - name: 'Start Sign'
        env:
          SCKEY1: ${{ secrets.SCKEY1}}
          SCKEY2: ${{ secrets.SCKEY2}}
          SCKEY3: ${{ secrets.SCKEY3}}
        run: python3 main.py
